# Copyright (c) 2018, salesforce.com, inc.
# All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause
# For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause

description: >
  Merges one green, mergeable patch/minor dependabot PR

parameters:
  max-version-bump:
    description: maximum allowed version bump.  You probably don't want to automate major version bumps!
    type: enum
    enum: ['patch', 'minor', 'major']
    default: 'minor'
  skip-ci:
    description: Optionally skip ci builds on merges into main
    type: boolean
    default: false
  merge-method:
    description: merge method to use
    type: enum
    enum: ['merge', 'squash', 'rebase']
    default: 'merge' 

executor:
  name: linux

steps:
  - install-node
  - checkout
  - install-sf-release
  - run:
      name: Install dependencies
      command: yarn

  - when:
      condition: <<parameters.skip-ci>>
      steps:
        - run:
            name: Upgrade one dependency
            command: |
              sf-release dependabot:automerge --skip-ci \
              --max-version-bump "<<parameters.max-version-bump>>" \
              --merge-method "<<parameters.merge-method>>"

  - when:
      condition:
        not: <<parameters.skip-ci>>
      steps:
        - run:
            name: Upgrade one dependency
            command: |
              sf-release dependabot:automerge \
              --max-version-bump "<<parameters.max-version-bump>>" \
              --merge-method "<<parameters.merge-method>>"

